my_string = input(('Введите строку:\n'))
print(my_string[2])
print(my_string[-2])
print(my_string[:5])
print(my_string[:-2])
print(my_string[::2])
print(my_string[1::2])
print(my_string[::-1])
print(my_string[::-2])
print(len(my_string))
